package org.iiitb.mt2013.os.conts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public interface Constants
{

	String CLOCK_REPLACEMENT_ALGO_NAME = "CLOCK-POLICY";

	int RECT_WITHOUT_ELEMENT_WIDTH = 10;

	int GAP_BETWEEN_TWO_MEMORY_PRNTS = 10;

	String FIFO_REPLACEMENT_ALGO = "FIFO-POLICY";

	int MAX_VALUE = 9999999;

	String LRU_REPLACEMENT_ALGO = "LRU-POLICY";

	String COUNT_REPLACEMENT_ALGO_NAME = "COUNT-POLICY";

	String OPTIMUM_REPLACE_ALGO = "OPTIMUM-POLICY";

	String WORKINGSETMODEL = "WORKING-SET-MODEL-POLICY";

	List<String> ALGORITHMS_NAMES = new ArrayList<String>(Arrays.asList(CLOCK_REPLACEMENT_ALGO_NAME,
			FIFO_REPLACEMENT_ALGO, LRU_REPLACEMENT_ALGO, COUNT_REPLACEMENT_ALGO_NAME, OPTIMUM_REPLACE_ALGO,
			WORKINGSETMODEL));
}
